### ISSUE TITLE
Why tqdm error ?

### ISSUE THREAD

**Issue by jeongkwan2021** [zwicker-group/py-pde#109]
You would better specify the versions of python and anaconda/conda for the codes uploaded.  The programs do not seem to be robust. Your tutorial2 seems to have a more serious library issue. 

The following error message is typical:
# 
solver = pde.ExplicitSolver(eq)
controller = pde.Controller(solver, t_range=1)
sol1 = controller.run(field, dt=1e-3);
/srv/conda/envs/notebook/lib/python3.7/site-packages/pde/tools/output.py:61: UserWarning: `tqdm` package is not available. Progress will be indicated by dots.
  "`tqdm` package is not available. Progress will be indicated by dots."

In the example programs of 'Different solvers.ipynb' & 'Solve PDEs.ipynb', this error message is showing up but not in 'Discretized Fields.ipynb'.   Several similar messages are showing up in tutorial2.

**Comment by david-zwicker** [comment]
This is expected behavior. In essence, nice progress bars are only shown when the python package `tqdm` is installed, but I did not want to make this package a hard dependence. Instead, if `tqdm` is not available progress is only indicated by dots and the warning you saw is shown. However, I'm happy to alter and adapt this behavior. What behavior did you expect?

**Comment by david-zwicker** [comment]
We changed the default trackers such that progress is not indicated when `tqdm` is not installed. I think this closes this issue.
