### ISSUE TITLE
Unexpected result for exponential decay

### ISSUE THREAD

**Issue by PeterHampshire** [zwicker-group/py-pde#114]
Dear Dr Zwicker

Thanks for creating this public pde solver. I am new to using it but it looks great!

I have an issue trying to simulate an exponential decay in 2 dimensions. The code is
"
import numpy as np
from pde import PDE, FieldCollection, PlotTracker, ScalarField, UnitGrid, CartesianGrid
import functools

tauE=5
eq = PDE(
   {
       "E": f"-E/{tauE}", 
   },
   bc="periodic"
)

#Define Cartesian Grid
grid = CartesianGrid([[0, 1], [0, 1]], [32, 32], periodic=[True,True])  # generate grid
E = ScalarField(grid,1, label="Field $E$")
state = FieldCollection([E])

# simulate the pde
tracker = PlotTracker(interval=0.5, plot_args={"vmin": -3, "vmax": 3})
sol = eq.solve(state, t_range=10, dt=1e-5, tracker=tracker) 
"
I expect the value at every point in the grid to decay to 0. However instead the value decays to 0 and then blows up to large negative values. Can you see where the error is in my code?

**Comment by david-zwicker** [comment]
Thank you for this bug report! The behavior you observe is due to a subtlety of how we parse the right hand side of the differential equation, which happens using `sympy`. It turns out, sympy interprets the symbol `E` as Euler's number, so that your right hand side becomes a constant negative number, explaining the observed result. The solution is to rename your field variable from `E` to anything else. I just updated `py-pde` to raise an error when a field is named `E` to prevent this behavior in the future.

**Comment by PeterHampshire** [comment]
Thanks for the help and the prompt reply!
