### ISSUE TITLE
Plot Issue

### ISSUE THREAD

**Issue by yangheart** [zwicker-group/py-pde#127]
Dear Dr. Zwicker,

I tried some examples by py-pde today and found something different about plotting. For the previous version, for any given t_range and interval, say t_range=20 and interval=1, the program will draw the pictures of solutions at every interge time from 0 to 20. In the current version, if I still use the same setting, the program will only draw the pictures of solutions at some certain integer times but not every step.
 How could I do for recovering the previous way, like plotting for every time step?

Thank you so much!

**Comment by david-zwicker** [comment]
The issue you see is caused by a newer change, which implemented frame skipping to improve the performance of live plotting. I agree that skipping frames is not always helpful (in particular when creating movies and image sequences). I now implemented an argument for the `PlotTracker`, which allows to control the behavior by specifying the maximal frame rate with which the plots are updated. Setting this value to a higher value (e.g., `np.inf`) ensures that no frames are skipped. A small example for how to use this plot tracker is

```python
from pde import DiffusionPDE, ScalarField, UnitGrid, PlotTracker

grid = UnitGrid([64, 64])  # generate grid
state = ScalarField.random_uniform(grid, 0.2, 0.3)  # generate initial condition

eq = DiffusionPDE(diffusivity=0.1)  # define the pde
result = eq.solve(state, t_range=10)

plot_tracker = PlotTracker(show=True, max_fps=np.inf)
eq.solve(state, t_range=10, tracker=['progress', plot_tracker])
```

Note the penultimate line, which defines the plot tracker with arguments ensuring that all frames are shown.

**Comment by yangheart** [comment]
Thank you so much for helping me and giving a clear explanation. It works for me!
