### ISSUE TITLE
Making Movies File Naming Problem

### ISSUE THREAD

**Issue by MatthewBelzer** [zwicker-group/py-pde#13]
I am trying to create a movie in Jupyter Notebook on Windows 10 using the following code

```
import numpy as np
from pde import FieldCollection
from pde import (DiffusionPDE, UnitGrid, ScalarField, MemoryStorage,
                 PlotTracker, PrintTracker, RealtimeIntervals)
from pde.visualization import movies
import pde

storage = MemoryStorage()

trackers = [
    'progress',                    # show progress bar during simulation
    'steady_state',                # abort when steady state is reached
    storage.tracker(interval=1),   # store data every simulation time unit
    PlotTracker(show=True),        # show images during simulation
    # print some output every 5 real seconds:
    PrintTracker(interval=RealtimeIntervals(duration=1))
]

grid = pde.UnitGrid([64, 64])
field2 = ScalarField.random_uniform(grid, 1, 1)  # generate initial condition
field1 = ScalarField.random_harmonic(grid)  # generate initial condition
state = FieldCollection.scalar_random_uniform(2, grid)
state = FieldCollection([field1,field2]);


eq = pde.WavePDE(speed=0.1);
result = eq.solve(state, t_range=3, dt=1, tracker = trackers)
result.plot(show=True)                                 # plot the resulting field
movies.movie_multiple(storage, filename = r'C:\Users\matth\URECA Simulation\testfile.mp4')
```

it gives me this error: 
`FileNotFoundError: [WinError 2] The system cannot find the file specified.` 
I have tried saving it to files without a path, files with a path, and files in the jupyter notebook environment but I have been unable to get it to work.

**Comment by david-zwicker** [comment]
Thank you for the bug report. Unfortunately, I don't have any easy access to the Windows platform and can thus not test and reproduce the error. However, I'm not surprised that the movie system does not work on Windows, since it relies on the `ffmpeg` command, which is likely called `ffmpeg.exe` on Windows. I was already thinking about switching to the movie writers of `matplotlib`, which should also work on Windows. In the meantime, you could at least save the frames as individual files using 

```python
movie = pde.visualization.movies.Movie(image_folder=FOLDER)
plot_tracker = pde.trackers.PlotTracker(movie=movie)
eq.solve(state, t_range, dt, tracker=['progress', plot_tracker])
```
This should write all frames into the folder `FOLDER` as individual images. You could then use any other tool to concatenate the images into a movie. Note that this method might require a pretty new version of the code.

**Comment by david-zwicker** [comment]
It turned out that the matplotlib function was quite easy to integrate and I did this in the latest code (version 0.8.2). Could you please lest whether the code you were using works now?

**Comment by MatthewBelzer** [comment]
It works fine now thanks!
