### ISSUE TITLE
Storing complex fields in FileStorage

### ISSUE THREAD

**Issue by gregor-anich-uibk** [zwicker-group/py-pde#193]
Hi,

it seems that the `FileStorage` class can only handle real-valued fields, a simple modification of the Schrödinger equation example to use `FileStorage` instead of `MemoryStorage` should reproduce the problem. I think it stems from the fact that in `_create_hdf_dataset()` of `FileStorage` in pde/storage/file.py the `dtype` is always the default `np.double`.
If anybody else has the same problem, a workaround might be to subclass `StorageTracker` and reimplement the `handle()` function to store only the absolute value of the field instead of complex.
Would be cool if this can be fixed, the package looks very nice with a very good high-level API, I like it a lot!

Greetings from Austria,
Gregor

**Comment by david-zwicker** [comment]
Thanks for the report. I was able to reproduce the error and agree it would be nice to support this generally. The latest master branch contains a fix, which hopefully mitigates this problem (and resolves over issues with fields of non-standard dtype). Could you please check whether the latest master branch fixes your issue?

**Comment by gregor-anich-uibk** [comment]
Hello, thanks for the quick fix, now it works as expected :-)
When plotting the complex scalar field with `plot_kymographs()` it seems that the real part is plotted. One can easily change it with the "scalar" argument, but maybe for a complex field it would make sense to default to the norm. It could also be useful to be able to plot the "phase" or "angle" or whatever you want to call it (which of course should be possible by simply passing `scalar=np.angle`)
The documentation for `ScalarField.to_scalar` lists abs,norm and norm_squared as possible options, from the documentation it's not clear to me what the difference between abs and norm is (or is it the same?)

**Comment by david-zwicker** [comment]
Yes, all your observations are correct. Sorry for the confusion – complex fields are not very well tested.

Typically, the real part is analyzed for complex fields, but I will change it to the norm eventually, which definitely makes more sense. There is no difference between `abs` and `norm` (although I thought there was) – I adjusted the docs to reflect this.

I'd be happy if you could test complex fields further since this is a rather new feature and might thus not be supported properly everywhere. I'm also happy to review pull requests to improve code, examples, or the documentation.
