### ISSUE TITLE
Custom Boundary Conditions

### ISSUE THREAD

**Issue by danizil** [zwicker-group/py-pde#35]
Thanks a lot for this! 
I can't seem to find an explanation on how to set up my own boundary conditions as an array though...
I managed to do it using: 
`bc = {"type" : "value", "value" : <the boundary list>}`
though it took some faith in the creators. Maybe it could be added to the documentation.
Thanks!

**Comment by david-zwicker** [comment]
Yes, this is not yet mentioned in the documentation, although there is an [example that shows how to set the value using a mathematical expression](https://py-pde.readthedocs.io/en/latest/examples_gallery/boundary_conditions.html). Setting the boundary condition using an array is a bit error-prone, since the user has to take a lot of care to make sure the dimensions and shapes of the value are correct. However, it looks as if you figured out the correct way, so congratulations!

**Comment by danizil** [comment]
yes I saw! is there a list if all possible expressions?
I'm using it for image processing so I need to give the actual boundaries...

**Comment by david-zwicker** [comment]
I now adjusted the documentation a bit, but I must admit that it is difficult to mention all details. However, I'm always happy for pull request that improve the documentation. I assume that this particular issue can now be closed, but if you disagree, feel free to reopen!

**Comment by aminih01** [comment]
Is it also possible to include expressions as functions of the fields for the boundary conditions?

**Comment by david-zwicker** [comment]
It's possible to given an expression that defines the [value](https://py-pde.readthedocs.io/en/latest/packages/pde.grids.boundaries.local.html#pde.grids.boundaries.local.ExpressionValueBC) or the [derivative](https://py-pde.readthedocs.io/en/latest/packages/pde.grids.boundaries.local.html#pde.grids.boundaries.local.ExpressionDerivativeBC) of a field at the boundary. The expression might even depend on time; see [this example](https://py-pde.readthedocs.io/en/latest/examples_gallery/time_dependent_bcs.html#sphx-glr-examples-gallery-time-dependent-bcs-py).
